### PR TITLE
Renamed 'hasOnlick' to 'hasOnclick'

### PR DESCRIPTION
**Pull request by Stapelpanda**
`CTRL+SHIFT+F` hasOnlick => Change to hasOnclick

### CODE REVIEW

**Review by bartist — CHANGES_REQUESTED** [review]
I think he will propably require capitalization of the C, so hasOnClick

**Comment by Stapelpanda** [comment]
in the function itself "onclick" is written whithout caps.

**Comment by bartist** [comment]
Hmm, in that case you can create a PR. If he wants the capital C, he'll probably let you know

**Review by bartist — APPROVED** [review]

**Review by baranusta — APPROVED** [review]

**Comment by bartist** [comment]
@Stapelpanda I forgot one thing: could you add hasOnclick to the globals of controller.js and directives.js? that fixes 2 StandardJS errors that I left out

**Review by kiliangrashoff — APPROVED** [review]
LGTM!

**Pull request closed without merging**
